/// Core constants used throughout the Clonify CLI tool.
///
/// This class provides static constants and utility methods for accessing
/// file paths, configuration templates, and tool metadata.
abstract class Constants {
  /// Generates the expected path for the iOS IPA file.
  ///
  /// The path is constructed based on the standard Flutter build output
  /// and includes the provided [packageName].
  ///
  /// [packageName] The package name, which is typically used in the IPA filename.
  ///
  /// Returns a [String] representing the full path to the IPA file.
  static String ipaPath(String packageName) =>
      './build/ios/ipa/$packageName.ipa';

  /// The standard path for the Android App Bundle (AAB) file.
  ///
  /// This constant represents the typical output path for a release AAB
  /// generated by Flutter builds.
  static String aabPath = './build/app/outputs/bundle/release/app-release.aab';

  /// The official name of the Clonify CLI tool.
  static const String toolName = 'clonify';

  /// The current version of the Clonify CLI tool.
  /// Note: This is now read dynamically from pubspec.yaml via the --version flag.
  @Deprecated('Use --version flag to get the current version')
  static const String version = '0.3.0';

  /// The relative path to the main Clonify settings file.
  ///
  /// This file (`clonify_settings.yaml`) stores global configurations
  /// for the Clonify CLI tool.
  static String clonifySettingsFilePath = './clonify/clonify_settings.yaml';

  /// Generates the path to a client's configuration file.
  ///
  /// This method constructs the full path to the `config.json` file
  /// for a specific client, located within the `./clonify/clones/` directory.
  ///
  /// [clientId] The ID of the client for which to get the config file path.
  ///
  /// Returns a [String] representing the full path to the client's config file.
  static configFilePath(String clientId) =>
      './clonify/clones/$clientId/config.json';

  /// The relative path to the project's `pubspec.yaml` file.
  static const String pubspecFilePath = './pubspec.yaml';

  /// A template string for the `flutter_launcher_icons.yaml` configuration file.
  ///
  /// This template is used to generate the configuration for the `flutter_launcher_icons`
  /// package, which helps in creating adaptive launcher icons for Android and iOS.
  static const String flutterLauncherIconsYaml = '''
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: ""
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: ""
  min_sdk_android: 21
''';

  /// A template string for the `flutter_native_splash.yaml` configuration file.
  ///
  /// This template is used to generate the configuration for the `flutter_native_splash`
  /// package, which helps in creating native splash screens for Flutter applications.
  static const String flutterNativeSplashYaml = '''
flutter_native_splash:
  color: "#FFFFFF"
  image: ""
  android_12:
    image: 
  web: false
  ios_content_mode: scaleToFill
  fullscreen: true
''';
}
